build_from:
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19

args:
  # 使用新仓库
  RATHOLE_OWNER: "rathole-org"
  RATHOLE_REPO: "rathole"
  RATHOLE_TAG: "v0.5.0"
  VT_TEST_ARG: "hello_from_build_yaml"
