build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19

args:
  RATHOLE_TAG: "rathole-v0.5.0"
  RATHOLE_OWNER: "ytfangh"
  RATHOLE_REPO: "rathole-binaries"
